# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Layer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Layer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLayer(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Layer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Layer
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Layer
    def UsePermanentFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def LayerStart(builder):
    builder.StartObject(2)

def Start(builder):
    LayerStart(builder)

def LayerAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    LayerAddId(builder, id)

def LayerAddUsePermanentFrame(builder, usePermanentFrame):
    builder.PrependBoolSlot(1, usePermanentFrame, 0)

def AddUsePermanentFrame(builder, usePermanentFrame):
    LayerAddUsePermanentFrame(builder, usePermanentFrame)

def LayerEnd(builder):
    return builder.EndObject()

def End(builder):
    return LayerEnd(builder)
