// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vector2f } from '../../rewind-viewer/fbs/vector2f.js';


export class MousePath {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MousePath {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMousePath(bb:flatbuffers.ByteBuffer, obj?:MousePath):MousePath {
  return (obj || new MousePath()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMousePath(bb:flatbuffers.ByteBuffer, obj?:MousePath):MousePath {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MousePath()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

points(index: number, obj?:Vector2f):Vector2f|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vector2f()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

pointsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMousePath(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPoints(builder:flatbuffers.Builder, pointsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, pointsOffset, 0);
}

static startPointsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static endMousePath(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMousePath(builder:flatbuffers.Builder, pointsOffset:flatbuffers.Offset):flatbuffers.Offset {
  MousePath.startMousePath(builder);
  MousePath.addPoints(builder, pointsOffset);
  return MousePath.endMousePath(builder);
}
}
