// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Command, unionToCommand, unionListToCommand } from '../../rewind-viewer/fbs/command.js';


export class RewindMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RewindMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRewindMessage(bb:flatbuffers.ByteBuffer, obj?:RewindMessage):RewindMessage {
  return (obj || new RewindMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRewindMessage(bb:flatbuffers.ByteBuffer, obj?:RewindMessage):RewindMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RewindMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

commandType():Command {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Command.NONE;
}

command<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startRewindMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCommandType(builder:flatbuffers.Builder, commandType:Command) {
  builder.addFieldInt8(0, commandType, Command.NONE);
}

static addCommand(builder:flatbuffers.Builder, commandOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, commandOffset, 0);
}

static endRewindMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // command
  return offset;
}

static finishRewindMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedRewindMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createRewindMessage(builder:flatbuffers.Builder, commandType:Command, commandOffset:flatbuffers.Offset):flatbuffers.Offset {
  RewindMessage.startRewindMessage(builder);
  RewindMessage.addCommandType(builder, commandType);
  RewindMessage.addCommand(builder, commandOffset);
  return RewindMessage.endRewindMessage(builder);
}
}
