// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SelectInput {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SelectInput {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSelectInput(bb:flatbuffers.ByteBuffer, obj?:SelectInput):SelectInput {
  return (obj || new SelectInput()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSelectInput(bb:flatbuffers.ByteBuffer, obj?:SelectInput):SelectInput {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SelectInput()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

options(index: number):string
options(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
options(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

optionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

selectedOption():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startSelectInput(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addOptions(builder:flatbuffers.Builder, optionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, optionsOffset, 0);
}

static createOptionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startOptionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSelectedOption(builder:flatbuffers.Builder, selectedOption:number) {
  builder.addFieldInt16(1, selectedOption, 0);
}

static endSelectInput(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // options
  return offset;
}

static createSelectInput(builder:flatbuffers.Builder, optionsOffset:flatbuffers.Offset, selectedOption:number):flatbuffers.Offset {
  SelectInput.startSelectInput(builder);
  SelectInput.addOptions(builder, optionsOffset);
  SelectInput.addSelectedOption(builder, selectedOption);
  return SelectInput.endSelectInput(builder);
}
}
