// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type ActionInput byte

const (
	ActionInputNONE        ActionInput = 0
	ActionInputBoolInput   ActionInput = 1
	ActionInputButtonInput ActionInput = 2
	ActionInputFloatInput  ActionInput = 3
	ActionInputIntInput    ActionInput = 4
	ActionInputSelectInput ActionInput = 5
	ActionInputStringInput ActionInput = 6
)

var EnumNamesActionInput = map[ActionInput]string{
	ActionInputNONE:        "NONE",
	ActionInputBoolInput:   "BoolInput",
	ActionInputButtonInput: "ButtonInput",
	ActionInputFloatInput:  "FloatInput",
	ActionInputIntInput:    "IntInput",
	ActionInputSelectInput: "SelectInput",
	ActionInputStringInput: "StringInput",
}

var EnumValuesActionInput = map[string]ActionInput{
	"NONE":        ActionInputNONE,
	"BoolInput":   ActionInputBoolInput,
	"ButtonInput": ActionInputButtonInput,
	"FloatInput":  ActionInputFloatInput,
	"IntInput":    ActionInputIntInput,
	"SelectInput": ActionInputSelectInput,
	"StringInput": ActionInputStringInput,
}

func (v ActionInput) String() string {
	if s, ok := EnumNamesActionInput[v]; ok {
		return s
	}
	return "ActionInput(" + strconv.FormatInt(int64(v), 10) + ")"
}
