// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ButtonInput struct {
	_tab flatbuffers.Table
}

func GetRootAsButtonInput(buf []byte, offset flatbuffers.UOffsetT) *ButtonInput {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ButtonInput{}
	x.Init(buf, n+offset)
	return x
}

func FinishButtonInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsButtonInput(buf []byte, offset flatbuffers.UOffsetT) *ButtonInput {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ButtonInput{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedButtonInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ButtonInput) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ButtonInput) Table() flatbuffers.Table {
	return rcv._tab
}

func ButtonInputStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ButtonInputEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
