// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type Command byte

const (
	CommandNONE          Command = 0
	CommandArc           Command = 1
	CommandCameraView    Command = 2
	CommandCircle        Command = 3
	CommandCircleSegment Command = 4
	CommandLogText       Command = 5
	CommandOptions       Command = 6
	CommandPolyline      Command = 7
	CommandPopup         Command = 8
	CommandPopupRound    Command = 9
	CommandReadEvents    Command = 10
	CommandRectangle     Command = 11
	CommandSubscribe     Command = 12
	CommandTiles         Command = 13
	CommandTriangle      Command = 14
	CommandUnsubscribe   Command = 15
	CommandPrimitives    Command = 16
	CommandEndFrame      Command = 17
)

var EnumNamesCommand = map[Command]string{
	CommandNONE:          "NONE",
	CommandArc:           "Arc",
	CommandCameraView:    "CameraView",
	CommandCircle:        "Circle",
	CommandCircleSegment: "CircleSegment",
	CommandLogText:       "LogText",
	CommandOptions:       "Options",
	CommandPolyline:      "Polyline",
	CommandPopup:         "Popup",
	CommandPopupRound:    "PopupRound",
	CommandReadEvents:    "ReadEvents",
	CommandRectangle:     "Rectangle",
	CommandSubscribe:     "Subscribe",
	CommandTiles:         "Tiles",
	CommandTriangle:      "Triangle",
	CommandUnsubscribe:   "Unsubscribe",
	CommandPrimitives:    "Primitives",
	CommandEndFrame:      "EndFrame",
}

var EnumValuesCommand = map[string]Command{
	"NONE":          CommandNONE,
	"Arc":           CommandArc,
	"CameraView":    CommandCameraView,
	"Circle":        CommandCircle,
	"CircleSegment": CommandCircleSegment,
	"LogText":       CommandLogText,
	"Options":       CommandOptions,
	"Polyline":      CommandPolyline,
	"Popup":         CommandPopup,
	"PopupRound":    CommandPopupRound,
	"ReadEvents":    CommandReadEvents,
	"Rectangle":     CommandRectangle,
	"Subscribe":     CommandSubscribe,
	"Tiles":         CommandTiles,
	"Triangle":      CommandTriangle,
	"Unsubscribe":   CommandUnsubscribe,
	"Primitives":    CommandPrimitives,
	"EndFrame":      CommandEndFrame,
}

func (v Command) String() string {
	if s, ok := EnumNamesCommand[v]; ok {
		return s
	}
	return "Command(" + strconv.FormatInt(int64(v), 10) + ")"
}
