// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReadEvents struct {
	_tab flatbuffers.Table
}

func GetRootAsReadEvents(buf []byte, offset flatbuffers.UOffsetT) *ReadEvents {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReadEvents{}
	x.Init(buf, n+offset)
	return x
}

func FinishReadEventsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsReadEvents(buf []byte, offset flatbuffers.UOffsetT) *ReadEvents {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReadEvents{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedReadEventsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ReadEvents) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReadEvents) Table() flatbuffers.Table {
	return rcv._tab
}

func ReadEventsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ReadEventsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
