// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Text struct {
	_tab flatbuffers.Table
}

func GetRootAsText(buf []byte, offset flatbuffers.UOffsetT) *Text {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Text{}
	x.Init(buf, n+offset)
	return x
}

func FinishTextBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsText(buf []byte, offset flatbuffers.UOffsetT) *Text {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Text{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTextBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Text) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Text) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Text) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Text) Position(obj *Vector2f) *Vector2f {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector2f)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Text) Size() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Text) MutateSize(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *Text) Color() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Text) MutateColor(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func TextStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TextAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(text), 0)
}
func TextAddPosition(builder *flatbuffers.Builder, position flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(position), 0)
}
func TextAddSize(builder *flatbuffers.Builder, size float32) {
	builder.PrependFloat32Slot(2, size, 0.0)
}
func TextAddColor(builder *flatbuffers.Builder, color uint32) {
	builder.PrependUint32Slot(3, color, 0)
}
func TextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
