// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TilesT struct {
	Position *Vector2fT `json:"position"`
	CellSize *Vector2fT `json:"cell_size"`
	RowSize uint16 `json:"row_size"`
	Colors []uint32 `json:"colors"`
}

func (t *TilesT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	colorsOffset := flatbuffers.UOffsetT(0)
	if t.Colors != nil {
		colorsLength := len(t.Colors)
		TilesStartColorsVector(builder, colorsLength)
		for j := colorsLength - 1; j >= 0; j-- {
			builder.PrependUint32(t.Colors[j])
		}
		colorsOffset = builder.EndVector(colorsLength)
	}
	TilesStart(builder)
	positionOffset := t.Position.Pack(builder)
	TilesAddPosition(builder, positionOffset)
	cellSizeOffset := t.CellSize.Pack(builder)
	TilesAddCellSize(builder, cellSizeOffset)
	TilesAddRowSize(builder, t.RowSize)
	TilesAddColors(builder, colorsOffset)
	return TilesEnd(builder)
}

func (rcv *Tiles) UnPackTo(t *TilesT) {
	t.Position = rcv.Position(nil).UnPack()
	t.CellSize = rcv.CellSize(nil).UnPack()
	t.RowSize = rcv.RowSize()
	colorsLength := rcv.ColorsLength()
	t.Colors = make([]uint32, colorsLength)
	for j := 0; j < colorsLength; j++ {
		t.Colors[j] = rcv.Colors(j)
	}
}

func (rcv *Tiles) UnPack() *TilesT {
	if rcv == nil {
		return nil
	}
	t := &TilesT{}
	rcv.UnPackTo(t)
	return t
}

type Tiles struct {
	_tab flatbuffers.Table
}

func GetRootAsTiles(buf []byte, offset flatbuffers.UOffsetT) *Tiles {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Tiles{}
	x.Init(buf, n+offset)
	return x
}

func FinishTilesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTiles(buf []byte, offset flatbuffers.UOffsetT) *Tiles {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Tiles{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTilesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Tiles) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Tiles) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Tiles) Position(obj *Vector2f) *Vector2f {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector2f)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Tiles) CellSize(obj *Vector2f) *Vector2f {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector2f)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Tiles) RowSize() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Tiles) MutateRowSize(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *Tiles) Colors(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *Tiles) ColorsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Tiles) MutateColors(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func TilesStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TilesAddPosition(builder *flatbuffers.Builder, position flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(position), 0)
}
func TilesAddCellSize(builder *flatbuffers.Builder, cellSize flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(cellSize), 0)
}
func TilesAddRowSize(builder *flatbuffers.Builder, rowSize uint16) {
	builder.PrependUint16Slot(2, rowSize, 0)
}
func TilesAddColors(builder *flatbuffers.Builder, colors flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(colors), 0)
}
func TilesStartColorsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TilesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
