// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TriangleT struct {
	Color *ColorT `json:"color"`
	Points []*Vector2fT `json:"points"`
}

func (t *TriangleT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	colorOffset := t.Color.Pack(builder)
	pointsOffset := flatbuffers.UOffsetT(0)
	if t.Points != nil {
		pointsLength := len(t.Points)
		TriangleStartPointsVector(builder, pointsLength)
		for j := pointsLength - 1; j >= 0; j-- {
			t.Points[j].Pack(builder)
		}
		pointsOffset = builder.EndVector(pointsLength)
	}
	TriangleStart(builder)
	TriangleAddColor(builder, colorOffset)
	TriangleAddPoints(builder, pointsOffset)
	return TriangleEnd(builder)
}

func (rcv *Triangle) UnPackTo(t *TriangleT) {
	t.Color = rcv.Color(nil).UnPack()
	pointsLength := rcv.PointsLength()
	t.Points = make([]*Vector2fT, pointsLength)
	for j := 0; j < pointsLength; j++ {
		x := Vector2f{}
		rcv.Points(&x, j)
		t.Points[j] = x.UnPack()
	}
}

func (rcv *Triangle) UnPack() *TriangleT {
	if rcv == nil {
		return nil
	}
	t := &TriangleT{}
	rcv.UnPackTo(t)
	return t
}

type Triangle struct {
	_tab flatbuffers.Table
}

func GetRootAsTriangle(buf []byte, offset flatbuffers.UOffsetT) *Triangle {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Triangle{}
	x.Init(buf, n+offset)
	return x
}

func FinishTriangleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTriangle(buf []byte, offset flatbuffers.UOffsetT) *Triangle {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Triangle{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTriangleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Triangle) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Triangle) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Triangle) Color(obj *Color) *Color {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Color)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Triangle) Points(obj *Vector2f, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 8
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Triangle) PointsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TriangleStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TriangleAddColor(builder *flatbuffers.Builder, color flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(color), 0)
}
func TriangleAddPoints(builder *flatbuffers.Builder, points flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(points), 0)
}
func TriangleStartPointsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 4)
}
func TriangleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
