// automatically generated by the FlatBuffers compiler, do not modify

package rewind_viewer.fbs;

@SuppressWarnings("unused")
public final class ActionInput {
  private ActionInput() { }
  public static final byte NONE = 0;
  public static final byte BoolInput = 1;
  public static final byte ButtonInput = 2;
  public static final byte FloatInput = 3;
  public static final byte IntInput = 4;
  public static final byte SelectInput = 5;
  public static final byte StringInput = 6;

  public static final String[] names = { "NONE", "BoolInput", "ButtonInput", "FloatInput", "IntInput", "SelectInput", "StringInput", };

  public static String name(int e) { return names[e]; }
}

