// automatically generated by the FlatBuffers compiler, do not modify

package rewind_viewer.fbs;

@SuppressWarnings("unused")
public final class LayerOrigin {
  private LayerOrigin() { }
  public static final byte GAME = 0;
  public static final byte LEFT_TOP = 1;
  public static final byte LEFT_CENTER = 2;
  public static final byte LEFT_BOTTOM = 3;
  public static final byte RIGHT_TOP = 4;
  public static final byte RIGHT_CENTER = 5;
  public static final byte RIGHT_BOTTOM = 6;
  public static final byte TOP_CENTER = 7;
  public static final byte BOTTOM_CENTER = 8;

  public static final String[] names = { "GAME", "LEFT_TOP", "LEFT_CENTER", "LEFT_BOTTOM", "RIGHT_TOP", "RIGHT_CENTER", "RIGHT_BOTTOM", "TOP_CENTER", "BOTTOM_CENTER", };

  public static String name(int e) { return names[e]; }
}

