// automatically generated by the FlatBuffers compiler, do not modify

package rewind_viewer.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RewindMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static RewindMessage getRootAsRewindMessage(ByteBuffer _bb) { return getRootAsRewindMessage(_bb, new RewindMessage()); }
  public static RewindMessage getRootAsRewindMessage(ByteBuffer _bb, RewindMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RewindMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte commandType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table command(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createRewindMessage(FlatBufferBuilder builder,
      byte commandType,
      int commandOffset) {
    builder.startTable(2);
    RewindMessage.addCommand(builder, commandOffset);
    RewindMessage.addCommandType(builder, commandType);
    return RewindMessage.endRewindMessage(builder);
  }

  public static void startRewindMessage(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addCommandType(FlatBufferBuilder builder, byte commandType) { builder.addByte(0, commandType, 0); }
  public static void addCommand(FlatBufferBuilder builder, int commandOffset) { builder.addOffset(1, commandOffset, 0); }
  public static int endRewindMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // command
    return o;
  }
  public static void finishRewindMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedRewindMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RewindMessage get(int j) { return get(new RewindMessage(), j); }
    public RewindMessage get(RewindMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

