// automatically generated by the FlatBuffers compiler, do not modify

package rewind_viewer.fbs;

@SuppressWarnings("unused")
public final class ActionValue {
  private ActionValue() { }
  public static final byte NONE = 0;
  public static final byte IntValue = 1;
  public static final byte FloatValue = 2;
  public static final byte BoolValue = 3;
  public static final byte StringValue = 4;

  public static final String[] names = { "NONE", "IntValue", "FloatValue", "BoolValue", "StringValue", };

  public static String name(int e) { return names[e]; }
}

