// automatically generated by the FlatBuffers compiler, do not modify

package rewind_viewer.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class CameraViewT {
  private String name;
  private rewind_viewer.fbs.Vector2fT position;
  private float viewRadius;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public rewind_viewer.fbs.Vector2fT getPosition() { return position; }

  public void setPosition(rewind_viewer.fbs.Vector2fT position) { this.position = position; }

  public float getViewRadius() { return viewRadius; }

  public void setViewRadius(float viewRadius) { this.viewRadius = viewRadius; }


  public CameraViewT() {
    this.name = null;
    this.position = new rewind_viewer.fbs.Vector2fT();
    this.viewRadius = 0.0f;
  }
}

