// automatically generated by the FlatBuffers compiler, do not modify

package rewind_viewer.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class CircleSegmentT {
  private rewind_viewer.fbs.ColorT color;
  private rewind_viewer.fbs.Vector2fT center;
  private float radius;
  private float startAngle;
  private float endAngle;

  public rewind_viewer.fbs.ColorT getColor() { return color; }

  public void setColor(rewind_viewer.fbs.ColorT color) { this.color = color; }

  public rewind_viewer.fbs.Vector2fT getCenter() { return center; }

  public void setCenter(rewind_viewer.fbs.Vector2fT center) { this.center = center; }

  public float getRadius() { return radius; }

  public void setRadius(float radius) { this.radius = radius; }

  public float getStartAngle() { return startAngle; }

  public void setStartAngle(float startAngle) { this.startAngle = startAngle; }

  public float getEndAngle() { return endAngle; }

  public void setEndAngle(float endAngle) { this.endAngle = endAngle; }


  public CircleSegmentT() {
    this.color = null;
    this.center = new rewind_viewer.fbs.Vector2fT();
    this.radius = 0.0f;
    this.startAngle = 0.0f;
    this.endAngle = 0.0f;
  }
}

