// automatically generated by the FlatBuffers compiler, do not modify

package rewind_viewer.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class KeyEvent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static KeyEvent getRootAsKeyEvent(ByteBuffer _bb) { return getRootAsKeyEvent(_bb, new KeyEvent()); }
  public static KeyEvent getRootAsKeyEvent(ByteBuffer _bb, KeyEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public KeyEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte key() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public rewind_viewer.fbs.MousePath mousePaths(int j) { return mousePaths(new rewind_viewer.fbs.MousePath(), j); }
  public rewind_viewer.fbs.MousePath mousePaths(rewind_viewer.fbs.MousePath obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int mousePathsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public rewind_viewer.fbs.MousePath.Vector mousePathsVector() { return mousePathsVector(new rewind_viewer.fbs.MousePath.Vector()); }
  public rewind_viewer.fbs.MousePath.Vector mousePathsVector(rewind_viewer.fbs.MousePath.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKeyEvent(FlatBufferBuilder builder,
      byte key,
      int mousePathsOffset) {
    builder.startTable(2);
    KeyEvent.addMousePaths(builder, mousePathsOffset);
    KeyEvent.addKey(builder, key);
    return KeyEvent.endKeyEvent(builder);
  }

  public static void startKeyEvent(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addKey(FlatBufferBuilder builder, byte key) { builder.addByte(0, key, 0); }
  public static void addMousePaths(FlatBufferBuilder builder, int mousePathsOffset) { builder.addOffset(1, mousePathsOffset, 0); }
  public static int createMousePathsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMousePathsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKeyEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public KeyEvent get(int j) { return get(new KeyEvent(), j); }
    public KeyEvent get(KeyEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

