// automatically generated by the FlatBuffers compiler, do not modify

package rewind_viewer.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class MapT {
  private float width;
  private float height;
  private long xGrid;
  private long yGrid;

  public float getWidth() { return width; }

  public void setWidth(float width) { this.width = width; }

  public float getHeight() { return height; }

  public void setHeight(float height) { this.height = height; }

  public long getXGrid() { return xGrid; }

  public void setXGrid(long xGrid) { this.xGrid = xGrid; }

  public long getYGrid() { return yGrid; }

  public void setYGrid(long yGrid) { this.yGrid = yGrid; }


  public MapT() {
    this.width = 0.0f;
    this.height = 0.0f;
    this.xGrid = 0L;
    this.yGrid = 0L;
  }
}

