// automatically generated by the FlatBuffers compiler, do not modify

package rewind_viewer.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class PopupRoundT {
  private String text;
  private rewind_viewer.fbs.Vector2fT areaCenter;
  private float areaRadius;

  public String getText() { return text; }

  public void setText(String text) { this.text = text; }

  public rewind_viewer.fbs.Vector2fT getAreaCenter() { return areaCenter; }

  public void setAreaCenter(rewind_viewer.fbs.Vector2fT areaCenter) { this.areaCenter = areaCenter; }

  public float getAreaRadius() { return areaRadius; }

  public void setAreaRadius(float areaRadius) { this.areaRadius = areaRadius; }


  public PopupRoundT() {
    this.text = null;
    this.areaCenter = new rewind_viewer.fbs.Vector2fT();
    this.areaRadius = 0.0f;
  }
}

