// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rewind_viewer.fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BoolInput : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static BoolInput GetRootAsBoolInput(ByteBuffer _bb) { return GetRootAsBoolInput(_bb, new BoolInput()); }
  public static BoolInput GetRootAsBoolInput(ByteBuffer _bb, BoolInput obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BoolInput __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool DefaultValue { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<rewind_viewer.fbs.BoolInput> CreateBoolInput(FlatBufferBuilder builder,
      bool default_value = false) {
    builder.StartTable(1);
    BoolInput.AddDefaultValue(builder, default_value);
    return BoolInput.EndBoolInput(builder);
  }

  public static void StartBoolInput(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDefaultValue(FlatBufferBuilder builder, bool defaultValue) { builder.AddBool(0, defaultValue, false); }
  public static Offset<rewind_viewer.fbs.BoolInput> EndBoolInput(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<rewind_viewer.fbs.BoolInput>(o);
  }
}


static public class BoolInputVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*DefaultValue*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
