// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rewind_viewer.fbs
{

public enum LayerOrigin : sbyte
{
  GAME = 0,
  LEFT_TOP = 1,
  LEFT_CENTER = 2,
  LEFT_BOTTOM = 3,
  RIGHT_TOP = 4,
  RIGHT_CENTER = 5,
  RIGHT_BOTTOM = 6,
  TOP_CENTER = 7,
  BOTTOM_CENTER = 8,
};


}
