name: MacOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --target rewind-viewer --parallel

      - name: Copy assets
        run: |
          mkdir ./build/Release
          cp -R ./resources ./build/Release
          cp ./build/rewind-viewer ./build/Release/
          chmod +x ./build/Release/rewind-viewer
        shell: bash

      - name: Upload Binaries
        if: ${{ always() }}  # TODO: only on release tag.
        uses: actions/upload-artifact@v4
        with:
          name: rewind-viewer-macos
          path: build/Release
          retention-days: 3
