name: MacOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --target rewind-viewer --parallel
