name: MacOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Homebrew dependencies
        run: brew install freetype

      - name: Configure CMake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --target rewind-viewer --parallel

      - name: Copy assets
        run: |
          mkdir ./rewind-viewer
          cp -R ./resources ./rewind-viewer
          cp ./build/rewind-viewer ./rewind-viewer
        shell: bash

      - name: Create zip archive
        run: zip -r rewind-viewer_dev_macos.zip ./rewind-viewer

      - name: Upload Binaries
        if: ${{ always() }}  # TODO: only on release tag.
        uses: actions/upload-artifact@v4
        with:
          name: rewind-viewer_dev_macos
          path: rewind-viewer_dev_macos.zip
          retention-days: 3
