name: Windows Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --target rewind-viewer --parallel --config Release

      - name: ls
        run: ls ./build

      - name: Upload Binaries
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: rewind-viewer-windows
          path: build/Release
