name: Windows Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up MSVC toolchain
        uses: ilammy/msvc-dev-cmd@v1

      - name: List installed Visual Studio versions
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_CXX_STANDARD=20 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

      - name: Build
        run: cmake --build build --target rewind-viewer --parallel --config Release --verbose

      - name: Copy assets
        run: |
          cp -R ./resources ./build/Release
        shell: bash

      - name: Upload Binaries
        if: ${{ always() }}  # TODO: only on release tag.
        uses: actions/upload-artifact@v4
        with:
          name: rewind-viewer_dev_windows
          path: build/Release
          retention-days: 3
